/*
	Actionaz
	Copyright (C), 2008-2010 Jonathan Mercier-Ganady

	Actionaz is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option), any later version.

	Actionaz is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY), without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program. If not, see <http://www.gnu.org/licenses/>.

	Contact : jmgr@jmgr.info
*/

AKEY(None),
AKEY(BackSpace),
AKEY(Tab),
AKEY(Linefeed),
AKEY(Clear),
AKEY(Return),
AKEY(Pause),
AKEY(ScrollLock),
AKEY(SysReq),
AKEY(Escape),
AKEY(Henkan),
AKEY(Zenkaku),
AKEY(Delete),
AKEY(Home),
AKEY(Left),
AKEY(Up),
AKEY(Right),
AKEY(Down),
AKEY(PageUp),
AKEY(PageDown),
AKEY(End),
AKEY(Begin),
AKEY(Select),
AKEY(Print),
AKEY(Execute),
AKEY(Insert),
AKEY(Undo),
AKEY(Redo),
AKEY(Menu),
AKEY(Find),
AKEY(Cancel),
AKEY(Help),
AKEY(Break),
AKEY(AltGr),
AKEY(NumLock),
AKEY(KP_Space),
AKEY(KP_Tab),
AKEY(KP_Enter),
AKEY(KP_F1),
AKEY(KP_F2),
AKEY(KP_F3),
AKEY(KP_F4),
AKEY(KP_Home),
AKEY(KP_Left),
AKEY(KP_Up),
AKEY(KP_Right),
AKEY(KP_Down),
AKEY(KP_PageUp),
AKEY(KP_PageDown),
AKEY(KP_End),
AKEY(KP_Begin),
AKEY(KP_Insert),
AKEY(KP_Delete),
AKEY(KP_Equal),
AKEY(KP_Multiply),
AKEY(KP_Add),
AKEY(KP_Separator),
AKEY(KP_Subtract),
AKEY(KP_Decimal),
AKEY(KP_Divide),
AKEY(KP_0),
AKEY(KP_1),
AKEY(KP_2),
AKEY(KP_3),
AKEY(KP_4),
AKEY(KP_5),
AKEY(KP_6),
AKEY(KP_7),
AKEY(KP_8),
AKEY(KP_9),
AKEY(F1),
AKEY(F2),
AKEY(F3),
AKEY(F4),
AKEY(F5),
AKEY(F6),
AKEY(F7),
AKEY(F8),
AKEY(F9),
AKEY(F10),
AKEY(F11),
AKEY(F12),
AKEY(F13),
AKEY(F14),
AKEY(F15),
AKEY(F16),
AKEY(F17),
AKEY(F18),
AKEY(F19),
AKEY(F20),
AKEY(F21),
AKEY(F22),
AKEY(F23),
AKEY(F24),
AKEY(F25),
AKEY(F26),
AKEY(F27),
AKEY(F28),
AKEY(F29),
AKEY(F30),
AKEY(F31),
AKEY(F32),
AKEY(F33),
AKEY(F34),
AKEY(F35),
AKEY(Shift_L),
AKEY(Shift_R),
AKEY(Control_L),
AKEY(Control_R),
AKEY(CapsLock),
AKEY(ShiftLock),
AKEY(Meta_L),
AKEY(Meta_R),
AKEY(Alt_L),
AKEY(Alt_R),
AKEY(Super_L),
AKEY(Super_R),
AKEY(Hyper_L),
AKEY(Hyper_R),
AKEY(Compose),
AKEY(DeadGrave),
AKEY(DeadAcute),
AKEY(DeadCircumflex),
AKEY(DeadTilde),
AKEY(DeadMacron),
AKEY(DeadBreve),
AKEY(DeadAbovedot),
AKEY(DeadDiaeresis),
AKEY(DeadAbovering),
AKEY(DeadDoubleacute),
AKEY(DeadCaron),
AKEY(DeadCedilla),
AKEY(DeadOgonek),
AKEY(LeftTab),
AKEY(SetModifiers),
AKEY(ClearModifiers),
AKEY(NextGroup),
AKEY(PrevGroup),
AKEY(Eject),
AKEY(Sleep),
AKEY(WWWBack),
AKEY(WWWForward),
AKEY(WWWRefresh),
AKEY(WWWStop),
AKEY(WWWSearch),
AKEY(WWWFavorites),
AKEY(WWWHome),
AKEY(AudioMute),
AKEY(AudioDown),
AKEY(AudioUp),
AKEY(AudioNext),
AKEY(AudioPrev),
AKEY(AudioStop),
AKEY(AudioPlay),
AKEY(AppMail),
AKEY(AppMedia),
AKEY(AppUser1),
AKEY(AppUser2)
